<?php
/**
 * MageOS
 *
 * @category   MageOS
 * @package    MageOS_AdminActivityLog
 * @copyright  Copyright (C) 2018 Kiwi Commerce Ltd (https://kiwicommerce.co.uk/)
 * @copyright  Copyright (C) 2024 MageOS (https://mage-os.org/)
 * @license    https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

/** @var Escaper $escaper */
/** @var ActivityLogListing $block */

use Magento\Framework\Escaper;
use MageOS\AdminActivityLog\Block\Adminhtml\ActivityLogListing;

$collection = $block->getLogListing();
$adminDetails = $block->getAdminDetails();
?>
<table class="activity-log-modal">
    <tr>
        <td>
            <table class="admin-details-table">
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Admin')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?php
                        if (!empty($adminDetails['username'])) {
                            echo $escaper->escapeHtml($adminDetails['username']);
                            if (!empty($adminDetails['name'])) {
                                echo $escaper->escapeHtml(" (" . ucwords(strtolower($adminDetails['name'])) . ")");
                            }
                        }
                    ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Module')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['module']) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Action')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['fullaction']) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Scope')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['scope']) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Store')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['store_name']) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Path')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['path']) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('User Agent')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml(
                        $adminDetails['browser'],
                        ['strong', 'br']
                    ) ?></td>
                </tr>
                <tr class="admin-details-row">
                    <td class="admin-details-label"><?= $escaper->escapeHtml(__('Date')) ?></td>
                    <td class="admin-details-separator">:</td>
                    <td class="admin-details-value"><?= $escaper->escapeHtml($adminDetails['date']) ?></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr class="spacer-row">
        <td></td>
    </tr>
    <?php if (!empty($collection)): ?>
        <tr>
            <td>
                <table class="activity-details-table">
                    <thead>
                        <tr>
                            <th class="field-name-col"><?= $escaper->escapeHtml(__('Field Name')) ?></th>
                            <th class="value-col"><?= $escaper->escapeHtml(__('Old Value')) ?></th>
                            <th class="value-col"><?= $escaper->escapeHtml(__('New Value')) ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($collection as $item): ?>
                            <tr>
                                <td class="field-name-col">
                                    <?= $escaper->escapeHtml(ucfirst(str_replace('_', ' ', $item["field_name"]))) ?>
                                </td>
                                <td class="value-col">
                                    <textarea class="value-container" readonly><?php
                                    if (!$block->getActivityRepository()->isFieldProtected($item['field_name'])):
                                        echo $escaper->escapeHtml($item['old_value']);
                                    endif ?></textarea>
                                </td>
                                <td class="value-col">
                                    <textarea class="value-container" readonly><?php
                                    if (!$block->getActivityRepository()->isFieldProtected($item['field_name'])):
                                        echo $escaper->escapeHtml($item['new_value']);
                                    endif ?></textarea>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </td>
        </tr>
    <?php endif; ?>
</table>
